[package]
name = "csv-index"
version = "0.1.6"
authors = [ "Andrew Gallant <jamslam@gmail.com>",]
description = "On disk CSV indexing data structures."
documentation = "https://docs.rs/csv-index"
homepage = "https://github.com/BurntSushi/rust-csv"
repository = "https://github.com/BurntSushi/rust-csv"
readme = "README.md"
keywords = [ "csv", "comma", "parser", "delimited", "index",]
license = "Unlicense/MIT"
categories = [ "encoding", "parser-implementations",]
workspace = ".."
edition = "2018"

[lib]
bench = false

[dependencies]
byteorder = "1"
bolero = "0.8.0"
arbitrary = "1.3.2"

[badges.travis-ci]
repository = "BurntSushi/rust-csv"

[badges.appveyor]
repository = "BurntSushi/rust-csv"

[dependencies.csv]
path = ".."
version = "1.1.0"
