[package]
name = "slab"
version = "0.4.2"
license = "MIT"
authors = [ "Carl Lerche <me@carllerche.com>",]
description = "Pre-allocated storage for a uniform data type"
documentation = "https://docs.rs/slab/0.4.2/slab/"
homepage = "https://github.com/carllerche/slab"
repository = "https://github.com/carllerche/slab"
readme = "README.md"
keywords = [ "slab", "allocator",]
categories = [ "memory-management", "data-structures",]

[dependencies]
bolero = "0.8.0"
arbitrary = "1.3.2"

[profile.fuzz]
inherits = "dev"
opt-level = 1
incremental = false
codegen-units = 1
