[package]
name = "crossbeam-epoch"
version = "0.8.2"
authors = [ "The Crossbeam Project Developers",]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-epoch"
documentation = "https://docs.rs/crossbeam-epoch"
description = "Epoch-based garbage collection"
keywords = [ "lock-free", "rcu", "atomic", "garbage",]
categories = [ "concurrency", "memory-management", "no-std",]

[features]
default = [ "std",]
std = [ "alloc", "crossbeam-utils/std", "lazy_static",]
alloc = []
nightly = [ "crossbeam-utils/nightly",]
sanitize = []

[dependencies]
cfg-if = "0.1.10"
memoffset = "0.5.4"
bolero = "0.8.0"
arbitrary = "1.3.2"

[dev-dependencies]
rand = "0.7.3"

[dependencies.crossbeam-utils]
version = "0.7"
path = "../crossbeam-utils"
default-features = false

[dependencies.lazy_static]
version = "1.4.0"
optional = true

[dependencies.scopeguard]
version = "1.1.0"
default-features = false
