[package]
name = "ndarray-rand"
version = "0.11.0"
edition = "2018"
authors = [ "bluss",]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-ndarray/ndarray"
documentation = "https://docs.rs/ndarray-rand/"
readme = "README.md"
description = "Constructors for randomized arrays. `rand` integration for `ndarray`."
keywords = [ "multidimensional", "matrix", "rand", "ndarray",]

[dependencies]
rand_distr = "0.2.1"
bolero = "0.8.0"
arbitrary = "1.3.2"

[dev-dependencies]
rand_isaac = "0.2.0"

[dependencies.ndarray]
version = "0.13"
path = ".."

[dependencies.quickcheck]
version = "0.9"
default-features = false
optional = true

[dependencies.rand]
version = "0.7.0"
features = [ "small_rng",]

[dev-dependencies.quickcheck]
version = "0.9"
default-features = false

[package.metadata.release]
no-dev-version = true
tag-name = "ndarray-rand-{{version}}"
