[package]
name = "crossbeam-channel"
version = "0.4.3"
authors = [ "The Crossbeam Project Developers",]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-channel"
documentation = "https://docs.rs/crossbeam-channel"
description = "Multi-producer multi-consumer channels for message passing"
keywords = [ "channel", "mpmc", "select", "golang", "message",]
categories = [ "algorithms", "concurrency", "data-structures",]

[features]
default = [ "std",]
std = [ "crossbeam-utils/std",]

[dependencies]
cfg-if = "0.1.10"
bolero = "0.8.0"
arbitrary = "1.3.2"

[dev-dependencies]
num_cpus = "1.13.0"
rand = "0.7.3"
signal-hook = "0.1.15"

[dependencies.crossbeam-utils]
version = "0.7"
path = "../crossbeam-utils"
default-features = false
optional = true
