[package]
name = "hcid_js"
version = "0.0.6"
license = "Apache-2.0"

[lib]
name = "hcid_js"
crate-type = [ "cdylib",]

[dependencies]
wasm-bindgen = "=0.2.40"
wee_alloc = "=0.4.4"
bolero = "0.8.0"
arbitrary = "1.3.2"

[dependencies.hcid]
path = "../../hcid"
