[package]
name = "crossbeam-utils"
version = "0.7.2"
authors = [ "The Crossbeam Project Developers",]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-utils"
documentation = "https://docs.rs/crossbeam-utils"
description = "Utilities for concurrent programming"
keywords = [ "scoped", "thread", "atomic", "cache",]
categories = [ "algorithms", "concurrency", "data-structures", "no-std",]

[features]
default = [ "std",]
std = [ "lazy_static",]
nightly = []

[dependencies]
cfg-if = "0.1.10"
bolero = "0.8.0"
arbitrary = "1.3.2"

[build-dependencies]
autocfg = "1.0.0"

[dev-dependencies]
rand = "0.7.3"

[dependencies.lazy_static]
version = "1.4.0"
optional = true
